### ISSUE TITLE
Create stacks in Portainer

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/geocodes#1]
Define the env variables and secrets
Add stacks to portainer
https://geocodes-dev.earthcube.org:9443/#!/2/docker/stacks

Configure limits. What is being used on geodex.org

**Comment by valentinedwv** [comment]
Working
Create base machine
add stacks (services and geocodes)

**Comment by MBcode** [comment]
geocodes-dev.earthcube.org:9443 isn't reachable, will it be on another machine?

**Comment by valentinedwv** [comment]
Production stacks use DNS, now.
 https://portainer.geocodes-dev.earthcube.org/
