### ISSUE TITLE
Summary workflow (blocker)

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/geocodes#12]
- Document summary workflow, and incorporate into geocodes documentation.
- migrate cleaned up  summary code to a repository (geocodes, or new repo)

specifics:
* https://github.com/earthcube/geocodes/blob/f01bd917fe29d5d7e158ca60e7539f93e388c8e2/docs/setup_indexing_with_gleanerio.md?plain=1#L381
* somewhere in the tenant setup: https://github.com/earthcube/geocodes/blob/f01bd917fe29d5d7e158ca60e7539f93e388c8e2/docs/tenant/index.md?plain=1#L22
* and add to loading production data: https://github.com/earthcube/geocodes/blob/main/docs/production/creatingAndLoadingProduction.md?plain=1

**Comment by MBcode** [comment]
starting diagram / documentation of summary workflow
https://github.com/MBcode/ec/blob/master/summary.md

**Comment by MBcode** [comment]
The 1st part of getting a crawl uses a [workaround](https://github.com/gleanerio/gleaner/issues/126) to get quads/repo for the [summarization](https://github.com/MBcode/ec/blob/master/summary.md)

**Comment by valentinedwv** [comment]
Needs  documentation:

-  instructions on how to run it,
- dependencies,
- bring up to production quality (aka remove hard coding, use argparse or click to create version that takes command line parameters),
- create repo or integrate into team repo.

**Comment by MBcode** [comment]
btw the fix_runX.sh process can take summoned as well, it just takes longer; then it makes the quads, and [now](https://github.com/earthcube/earthcube_utilities/blob/dev_mb/summarize/docs/call.md) materialize_summary.py takes the repo.nq to repo.tll for uploading  Just for safety sake, I think it is best to upload both of these files, to make sure the graph-urns are exactly the same btwn them.  The latest [PR](https://github.com/earthcube/earthcube_utilities/pull/23) gets this all going w/blaze vs fuseki, and later we still have the option of query of file via lib vs using any endpoint at all

**Comment by valentinedwv** [comment]
complete on dev
https://github.com/earthcube/earthcube_utilities/tree/dev/summarize
