### ISSUE TITLE
Improve Tenant Documentation

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/geocodes#25]
Did some improvements for[ Missing Instructions on Tenant](https://github.com/earthcube/geocodes/blob/main/docs/setting_up_user_interface/tenant/index.md)
More probably needs to be done.

See the notes in the[ Geocodes_documentation repository](https://github.com/earthcube/geocodes_documentation)

**Comment by ylyangtw** [comment]
just modified the client config part under the branch docs
