### ISSUE TITLE
blazegraph truncate journal

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/geocodes#33]
The famous, hey, can we document the exact steps for our systems, and not just the see [here](https://medium.com/@nvbach91/how-to-reclaim-disk-space-in-blazegraph-95a47575f8a8), so we can do this repeatedly, with a script request to truncate the blazegraph journal.

```
total 5823840
-rw-r--r--    1 root     root     6583746560 Jul 17 18:31 blazegraph.jnl
-rw-r--r--    1 root     root             0 May 15 18:52 rules.log
```

**Comment by ylyangtw** [comment]
also check blazegraph truncate journal's usage

**Comment by valentinedwv** [comment]
Thought on possibly scripting this using the docker/portainer api... once we know if the start/stop technique works

using docker.py
* create a client like the [scheduler generate code](https://github.com/earthcube/scheduler/blob/e9a533472145f5f7547841639c92dcd8c907e7c9/dagster/implnets/templates/v1/implnet_ops_SOURCEVAL.py#L225), so we can use the portainer as the proxy  
* find the service, get the running container.
* execute the command to get rid of the journal cruft.
* update the service so that it does not restart. [config might be in this area](https://docs.docker.com/engine/api/v1.41/#tag/Service/operation/ServiceUpdate)
* stop container
* run command to copy truncated file to proper location
* start container.
* wait, query with simple call
* if it works, then update the service to restart if failed.

**Comment by valentinedwv** [comment]
I think i was reading this wrong, and based on experience with Fuseki issues with journal filling disk.

Reading the doc says it will recover journal when it hits 200m statements. 

I might be misunderstanding how the journaling works... might just be we have not hit the recylce limits.   https://github.com/blazegraph/database/wiki/CommonProblems#problem-i-am-using-the-journal-and-the-file-size-grows-very-quickly
[12:58](https://earthcube.slack.com/archives/C05C78G0L3U/p1693598282751469)
Looks like we are using the rw store this is from the docker file.  https://github.com/nawerprod/blazegraph/blob/master/RWStore.properties

**Comment by ylyangtw** [comment]
putting this off. we probably don't need to worry about this.
