### ISSUE TITLE
minio montioring - Prometheus

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/geocodes#34]
We may need to update our services to get some more detailed object monitoring
https://min.io/docs/minio/linux/operations/monitoring/collect-minio-metrics-using-prometheus.html

**Comment by ylyangtw** [comment]
More complicated than I think... we will need to modify geocode deployment to set up a container for Prometheus

**Comment by ylyangtw** [comment]
Maybe try this https://minioadmin.geocodes-aws.earthcube.org/api/v1/admin/info

**Comment by ylyangtw** [comment]
Postpone this as it's not fully important. Can resume it if we need more info from Prometheus.
